--RLS--

--COMPROBAMOS LA EXISTENCIA DE LA BASE DE DATOS--

DROP DATABASE IF EXISTS STASHMOTOR_RLS
GO

CREATE DATABASE STASHMOTOR_RLS
GO

USE STASHMOTOR_RLS
GO

--CREAMOS USUARIOS LOS CUALES SERAN NUESTROS VENDEDORES--

CREATE USER ELIZABETH WITHOUT LOGIN;
CREATE USER DAVID WITHOUT LOGIN;
CREATE USER SAIRELYS WITHOUT LOGIN;

--CREAMOS LA TABLA VENDEDOR--

CREATE TABLE CLIENTE (
	Nombre Varchar(50) NULL,
	Apellido Varchar(50) NULL,
	Email Varchar(50) NULL,
	Nombre_Vendedor VARCHAR (50) NULL --CAMPO QUE FILTRARA EL ACCESO--
);
GO

--CONCEDEMOS PERMISOS DE CONSULTA SOBRE LOS USUARIOS--

GRANT SELECT ON CLIENTE TO ELIZABETH;
GRANT SELECT ON CLIENTE TO DAVID;
GRANT SELECT ON CLIENTE TO SAIRELYS;

INSERT INTO CLIENTE VALUES
	('JOSE' , 'PEREZ', 'JOSEPEREZ@GMAIL.COM', 'SAIRELYS'),
	('ANA' , 'VERDE' ,'ANAVERDE@GMAIL.COM', 'DAVID'),
	('SABRINA' , 'PRIETO', 'SABRIPRIETO@GMAIL.COM', 'ELIZABETH'),
	('SORAYA' , 'GONZALEZ', 'JOSEPEREZ@GMAIL.COM', 'SAIRELYS')
GO

--OBSERVAMOS EN QUE USUARIO NOS ENCONTRAMOS--
PRINT USER
GO

--CREAMOS LA FUNCION--

CREATE OR ALTER FUNCTION FN_ROWLEVELSECURITY (@FilterColumnName sysname)
		RETURNS TABLE
		WITH SCHEMABINDING
		AS
RETURN SELECT 1 AS FN_INFORMACIONDECLIENTE
WHERE @FilterColumnName = USER_NAME();
GO

--ACTIVAMOS LA FUNCION / FILTRADO POLITICA DE SEGURIDAD--

CREATE SECURITY POLICY FILTRAR_CLIENTE
ADD FILTER PREDICATE dbo.FN_ROWLEVELSECURITY(Nombre_Vendedor) 
ON dbo.CLIENTE
WITH (STATE=ON);
GO

--REALIZAMOS UNA CONSULTA--

SELECT * FROM CLIENTE
GO

--OTORGAMOS PERMISOS A LOS VENDEDORES DE ACTUALIZAR--

GRANT UPDATE, INSERT ON CLIENTE TO DAVID;
GRANT UPDATE, INSERT ON CLIENTE TO ELIZABETH;
GRANT UPDATE, INSERT ON CLIENTE TO SAIRELYS;

--IMPERSONAMOS DE USUARIOS PARA COMPROBAR--

EXECUTE AS USER = 'DAVID'; --SOLO ES CAPAZ DE VER UN REGISTRO--
GO

EXECUTE AS USER = 'ELIZABETH';
GO

EXECUTE AS USER = 'SAIRELYS';
GO


REVERT
GO

--HACEMOS UNA ACTUALIZACION EN LA TABLA--

UPDATE CLIENTE 
	SET Email = 'SABRIPRIETO85@GMAIL.COM',
	Nombre_Vendedor ''




--PREDICADO DE BLOQUEO / EVITA LAS INSERSIONES Y LOS BORRADOS--











