--FILETABLE--

--HABILITAMOS FILESTREAM Y REINICIARMOS EL SERVICIO--

EXEC sp_configure filestream_access_level, 2
RECONFIGURE
GO

--COMPROBAMOS LA EXISTENCIA DE LA BASE DE DATOS--
DROP DATABASE IF EXISTS STASHMOTORFILETABLE
GO

--CREAMOS LA BASE DE DATOS--

CREATE DATABASE STASHMOTORFILETABLE
ON PRIMARY
(
    NAME = STASHMOTOR_DATOS,
    FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\FileTable\stashmotor.mdf'
),
FILEGROUP FileStreamFG CONTAINS FILESTREAM
(
    NAME = SQLFileTable,
    FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\FileTable\Contenedor_filetable' 
)
LOG ON
(
    NAME = SQLFileTable_Log,
    FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\FileTable\log_filetable.ldf'
)
WITH FILESTREAM
(
    NON_TRANSACTED_ACCESS = FULL,
    DIRECTORY_NAME = 'Contenedor_filetable'
);
GO

--CREACIÓN TABLA DE TIPO FILETABLE--

USE STASHMOTORFILETABLE
GO

DROP TABLE IF EXISTS FABRTICANTE
GO

CREATE TABLE FABRICANTE
AS FILETABLE
WITH 
(
    FileTable_Directory = 'FileTableContainer',
    FileTable_Collate_Filename = database_default
);
GO

--HAREMOS UN SELECT SOBRE DICHA TABLA PUDIENDO VERIFICAR QUE LA MISMA--
--SE ENCUENTRA VACIA Y REPETIMOS DICHA ACCION LUEGO DE HABER --
--AGREGADO IMAGENES A LA MISMA--

SELECT * FROM FABRICANTE
GO







