--VERIFICAMOS LA EXISTENCIA DE LA BASE DE DATOS--

DROP DATABASE IF EXISTS STASHMOTOR_TABLAINMEMORY
GO

CREATE DATABASE STASHMOTOR_TABLAINMEMORY
go

USE STASHMOTOR_TABLAINMEMORY
go

ALTER DATABASE CURRENT  
    SET MEMORY_OPTIMIZED_ELEVATE_TO_SNAPSHOT = ON;
GO

--CREAMOS EL FILEGROUP OPTIMIZADO--

ALTER DATABASE STASHMOTOR_TABLAINMEMORY
	ADD FILEGROUP STASHMOTOR_TABLAINMEMORY_MOD 
	CONTAINS MEMORY_OPTIMIZED_DATA
GO

--AÑADIMOS ARCHIVOS AL MEMORY_OPTIMIZED_DATA FILEGROUP--

ALTER DATABASE STASHMOTOR_TABLAINMEMORY
	ADD FILE (name='STASHMOTOR_TABLAINMEMORY_MOD1', 
	filename='C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\INMEMORY\STASHMOTOR_TABLAINMEMORY_MOD1') 
	TO FILEGROUP STASHMOTOR_TABLAINMEMORY_MOD  
go

-- Creación de la tabla optimizada para memoria
DROP TABLE IF EXISTS Inventario
GO

CREATE TABLE Invetario(
	[ID_Inventario] [int] IDENTITY(1,1) NOT NULL,
	[Conteo_fecha_de_inicio] [date] NULL,
	[Conteo_fecha_de_cierre] [date] NULL,
	[TOTAL_INVENTARIO] [int] NULL,
		CONSTRAINT [Inventario_PK] PRIMARY KEY NONCLUSTERED (
	[ID_Inventario] ASC
)
	)
WITH  
        (MEMORY_OPTIMIZED = ON,  
        DURABILITY = SCHEMA_AND_DATA)
GO




