--BACKUP ENCRIPTADO--

--VERIFICAMOS LA EXISTENCIA DE LA BASE DE DATOS--

DROP DATABASE IF EXISTS STASH_BACKUP_ENCRYPTED
GO

--CREAMOS LA BASE DE DATOS--

CREATE DATABASE STASH_BACKUP_ENCRYPTED
GO

USE STASH_BACKUP_ENCRYPTED
GO

CREATE TABLE EMPLEADO (
	ID_EMPLEADO INT IDENTITY (1,1),
	NOMBRE VARCHAR(50),
	APELLIDO VARCHAR (50),
	FECHA_INGRESO DATE,
	EMAIL VARCHAR (50),
	TELEFONO VARCHAR (20)
)
GO

--CREAMOS LA LLAVE--

--NOS ASEGURAMOS DE ENCONTRARNOS EN MASTER--

USE MASTER
GO

CREATE MASTER KEY ENCRYPTION BY PASSWORD='STASH1234.'
GO

-- CREAMOS UN CERTIFICADO--

CREATE CERTIFICATE STASH_MOTOR_CERT
WITH SUBJECT = 'Certificado para Backup'
GO

--VERIFICAMOS LOS CERTIFICADOS--

SELECT TOP 2 NAME, pvt_key_encryption_type, issuer_name FROM  SYS.certificates
ORDER BY NAME  DESC
GO

--VOLVEMOS A LA BASE DE DATOS--

USE STASH_BACKUP_ENCRYPTED
GO

CREATE DATABASE ENCRYPTION KEY
WITH ALGORITHM = AES_256
ENCRYPTION BY SERVER CERTIFICATE STASH_MOTOR_CERT;
GO

--ACTIVAMOS LA ENCRIPTACION--

ALTER DATABASE STASH_BACKUP_ENCRYPTED
SET ENCRYPTION ON;
GO

USE master
GO

--INDICAMOS LA RUTA DONDE DESEAMOS REALIZAR EL BACKUP Y SU VEZ--
--DEBEMOS INDICAR EL CERTIFICADO--

BACKUP DATABASE STASH_BACKUP_ENCRYPTED
TO DISK = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\Seguridad\BACKUP_ENCRIPTADO\STASH_BACKUP_ENCRYPTED.bak'
WITH
ENCRYPTION
(
ALGORITHM = AES_256,
SERVER CERTIFICATE = STASH_MOTOR_CERT
),
STATS = 10,INIT 
GO

--Warning: The certificate used for encrypting the database encryption key has not been backed up. You should immediately back up the certificate and the private key associated with the certificate. If the certificate ever becomes unavailable or if you must restore or attach the database on another server, you must have backups of both the certificate and the private key or you will not be able to open the database.
--Msg 3201, Level 16, State 1, Line 70
--Cannot open backup device 'C:\Users\AndresPrieto\Documents\SQL Server Management Studio\SEGURIDAD\STASH_BACKUP_ENCRYPTED.bak'. Operating system error 5(Acceso denegado.).
--Msg 3013, Level 16, State 1, Line 70
--BACKUP DATABASE is terminating abnormally.

--Completion time: 2023-03-11T03:26:09.5743827+01:00

--PARA PODER SOLUCIONAR ESTO, DEBEMOS REALIZAR UNA COPIA DEL CERTIFICADO--

BACKUP CERTIFICATE STASH_MOTOR_CERT
TO FILE = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\Seguridad\STASH_MOTOR_CERT'
WITH PRIVATE KEY (FILE = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\Seguridad\STASH_MOTOR_CERTKEY.pvk', ENCRYPTION BY PASSWORD = 'STASH1234.')
GO

--EJECUTAMOS NUEVAMENTE EL SCRIPT--

BACKUP DATABASE STASH_BACKUP_ENCRYPTED
TO DISK = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\Seguridad\BACKUP_ENCRIPTADO\STASH_BACKUP_ENCRYPTED.bak'
WITH
ENCRYPTION
(
ALGORITHM = AES_256,
SERVER CERTIFICATE = STASH_MOTOR_CERT
),
STATS = 10,INIT 
GO

--RESTAURANDO BACKUP--

RESTORE DATABASE STASH_BACKUP_ENCRYPTED 
    FROM  DISK = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\Seguridad\BACKUP_ENCRIPTADO\STASH_BACKUP_ENCRYPTED.bak' 
    WITH  FILE = 1,  NOUNLOAD,  STATS = 5; 
GO

















