--NOS ASEGURAMOS DE ESTAR EN MASTER--

USE MASTER
GO

--CREAMOS UN LOGIN ADMINISTRATIVO DE LA BASE DE DATOS--

CREATE LOGIN STASH_ADMIN WITH PASSWORD ='STASH1234.'
GO

USE STASHMOTOR_ENCRYPT
GO

--CREAMOS EL USUARIO DENTRO DE LA BASE DE DATOS--

CREATE USER STASH_ADMIN FOR LOGIN STASH_ADMIN
GO

CREATE TABLE CLIENTE (
	ID_CLIENTE VARCHAR(10) PRIMARY KEY  NOT NULL,
	NOMBRE VARCHAR(20),
	APELLIDO VARCHAR(20),
	EMAIL VARCHAR(50),
	TELEFONO VARBINARY(150))
GO

--OTORGAMOS PERMISOS AL USUARIO SELECT, INSERT, UPDATE, DELET EN LA TABLA CLIENTE A STASH_ADMIN--

GRANT SELECT, INSERT, UPDATE, DELETE ON CLIENTE TO STASH_ADMIN
GO

--GENERAMOS LA LLAVE SIMETRICA PARA PROCEDER A ENCRIPTAR--

CREATE SYMMETRIC KEY STASH_ADMIN_KEY
AUTHORIZATION STASH_ADMIN
WITH ALGORITHM=AES_256 
ENCRYPTION BY PASSWORD='STASH1234.'
GO

--IMPERSONAMOS COMO STASHADMIN

EXEC AS USER= 'STASH_ADMIN'
GO

REVERT

--UNA VEZ ESTANDO CON EL USUARIO STASH_ADMIN--
--INSERTAMOS LOS DATOS EN LA TABLA CLIENTE--

PRINT USER
GO

OPEN SYMMETRIC KEY [STASH_ADMIN_KEY] DECRYPTION BY PASSWORD='STASH1234.'
GO

INSERT INTO CLIENTE VALUES (4,'Enrique','Gomez','kikegomez@gmail.com',EncryptByKey(Key_GUID('STASH_ADMIN_KEY'),'82'))
INSERT INTO CLIENTE VALUES (5,'Mercedes','Lopez','merche@gmail.com',EncryptByKey(Key_GUID('STASH_ADMIN_KEY'),'25702985'))
INSERT INTO CLIENTE VALUES (6,'Sabrina','Prieto','sabriprieto@gmail.com',EncryptByKey(Key_GUID('STASH_ADMIN_KEY'),'75201098'))
GO

SELECT * FROM CLIENTE	
GO

--CERRAMOS LA LLAVE--

CLOSE ALL SYMMETRIC KEYS
GO

OPEN SYMMETRIC KEY [STASH_ADMIN_KEY] DECRYPTION BY PASSWORD='STASH1234.'
GO

SELECT ID_CLIENTE,NOMBRE + ' ' + APELLIDO AS [NOMBRE DEL CLIENTE],
CONVERT(VARCHAR,DecryptByKey(TELEFONO)) as 'TELEFONO DEL CLIENTE'
FROM CLIENTE
GO

--CERRAMOS LA LLAVE--

CLOSE ALL SYMMETRIC KEYS
GO


