--FUNCION ENCRIPTADA--

--UTILIZAMOS LA TABLA CLIENTE Y TARJETA COMO REFERENCIA--

CREATE FUNCTION FN_CLIENTE_TARJETA_INFO(@ID_CLIENTE VARCHAR(10))
RETURNS TABLE
AS
RETURN
(
    SELECT C.ID_CLIENTE, C.NOMBRE, C.APELLIDO, T.NUMERO, T.CVV
    FROM CLIENTE C
    INNER JOIN TARJETA T ON C.ID_CLIENTE = T.ID_CLIENTE
    WHERE C.ID_CLIENTE = @ID_CLIENTE
);
GO

SELECT * FROM FN_CLIENTE_TARJETA_INFO ('1');

--BORRAMOS LA FUNCION--

DROP FUNCTION FN_CLIENTE_TARJETA_INFO


--CREAMOS LA FUNCION, PERO ESTA VEZ ENCRIPTANDO EL CAMPO CVV--

CREATE FUNCTION FN_CLIENTE_TARJETA_INFO(@ID_CLIENTE VARCHAR(10))
RETURNS TABLE
AS
RETURN
(
    SELECT C.ID_CLIENTE, C.NOMBRE, C.APELLIDO, T.NUMERO, CONVERT(VARCHAR(50), ENCRYPTBYKEY(KEY_GUID('SymmetricKey'), T.CVV)) AS CVV
    FROM CLIENTE C
    INNER JOIN TARJETA T ON C.ID_CLIENTE = T.ID_CLIENTE
    WHERE C.ID_CLIENTE = @ID_CLIENTE
);
GO

--EJECUTAMOS NUEVAMENTE LA MISMA SELECT, PERO ESTA VEZ NO SOMOS CAPACES DE VISUALIZAR EL CAMPO CVV--

SELECT * FROM FN_CLIENTE_TARJETA_INFO ('1');


