
--VERIFICAMOS LA EXISTENCIA DE LA BASE DE DATOS--

DROP DATABASE IF EXISTS STASHMOTOR_ENCRYPT
GO

CREATE DATABASE STASHMOTOR_ENCRYPT
GO

CREATE TABLE CLIENTE (
	ID_CLIENTE VARCHAR(10) PRIMARY KEY  NOT NULL,
	NOMBRE VARCHAR(20),
	APELLIDO VARCHAR(20),
	EMAIL VARCHAR(50),
	TELEFONO VARCHAR(20))
GO

CREATE TABLE TARJETA (
	ID_TARJETA int IDENTITY(1,1) NOT NULL,
	NUMERO VARCHAR (16),
	CVV VARCHAR (3),
	Fecha_Caducidad DATE,
	ID_CLIENTE VARCHAR (10), 
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE));
GO


--PROCEDIMIENTO ALMACENADO ENCRIPTADO-

--CREAMOS EL PROCEDIMIENTO ALMAMACENADO--

CREATE PROCEDURE BUSCAR_TARJETA_DE_CLIENTE
    @ID_Cliente INT
WITH ENCRYPTION
AS
BEGIN
    SELECT ID_TARJETA, NUMERO, CVV, Fecha_Caducidad, ID_Cliente
    FROM Tarjeta
    WHERE ID_Cliente = @ID_Cliente
END

EXEC BUSCAR_TARJETA_DE_CLIENTE @ID_Cliente = 1
GO

SP_HELP BUSCAR_TARJETA_DE_CLIENTE
SP_HELPTEXT BUSCAR_TARJETA_DE_CLIENTE








