--TRIGGER ENCRIPTADO--

-- CREAMOS LA MASTERKEY A NIVEL SERVIDOR--

--PARA ELLO NOS ASEGURAMOS DE ENCONTRARNOS EN MASTER--
USE MASTER;
GO

CREATE MASTER KEY ENCRYPTION
BY PASSWORD='STASHTRIGGERDB';
GO

--CRAMOS EL CERTIFICADO UTILIZANDO MSSQL--

CREATE CERTIFICATE TDE_STASHMOTORCERTIFICADO
WITH 
SUBJECT='TRIGGERDB DATABASE ENCRYPTION';
GO

SELECT TOP 1 * 
FROM sys.certificates 
ORDER BY name DESC
GO

--CREAMOS UN BACKUP DEL CERTIFICADO--

BACKUP CERTIFICATE TDE_STASHMOTORCERTIFICADO
TO FILE = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\Seguridad\STASHTRIGGERDB_CERT'
WITH PRIVATE KEY (FILE='C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\Seguridad\STASHTRIGGERDB_CERTKEY.pvk',
ENCRYPTION BY PASSWORD='STASHTRIGGERDB') 
GO

--CREAMOS LA BASE DE DATOS--

--VERIFICAMOS LA EXISTENCIA PREVIAMENTE DE LA BASE DE DATOS--

DROP DATABASE IF EXISTS STASHMOTOR_ENCRYPT_TDE
GO

CREATE DATABASE STASHMOTOR_ENCRYPT_TDE
GO

USE STASHMOTOR_ENCRYPT_TDE
GO

--ENCENDIDO DE ENCRIPTACION--

CREATE DATABASE ENCRYPTION KEY
	 WITH ALGORITHM = AES_256
  ENCRYPTION BY SERVER CERTIFICATE TDE_STASHMOTORCERTIFICADO;
GO 

SELECT  * 
FROM sys.dm_database_encryption_keys
GO

ALTER DATABASE STASHMOTOR_ENCRYPT_TDE SET ENCRYPTION ON;
GO

--VERIFICAMOS QUE SE ENCUENTRE REALMENTE ENCRIPTADA--

SELECT DB_Name(17) AS 'STASHMOTOR_ENCRYPT_TDE', encryption_state 
FROM sys.dm_database_encryption_keys;
GO

--CREAMOS EL BACKUP DE LA BASE DE DATOS--

BACKUP DATABASE STASHMOTOR_ENCRYPT_TDE
TO DISK = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\Seguridad\BACKUPTDE\STASHMOTOR_TDE_Full.bak';
GO 








