--ROW ENCRYPTION--

--VERIFICAMOS LA EXISTENCIA DE LA BASE DE DATOS--

DROP DATABASE IF EXISTS STASH_RLS
GO

--CREAMOS LA BASE DE DATOS--

CREATE DATABASE STASH_RLS
GO

--INICIALMENTE CREAREMOS DISTINTOS VENDEDORES PARA NUESTRO EJEMPLO--

CREATE USER VENDEDOR_PRO WITHOUT LOGIN
GO

CREATE USER VENDEDOR_INTERMEDIO WITHOUT LOGIN
GO

CREATE USER VENDEDOR_INICIAL WITHOUT LOGIN
GO

--CREAMOS LA TABLA VENTA--

CREATE TABLE VENTA (
	ID_VENTA INT IDENTITY (1,1) PRIMARY KEY,
	ID_PRODUCTO INT NOT NULL,
	CANTIDAD INT NOT NULL,
	FECHA_VENTA DATE NOT NULL,
	VENDEDOR VARCHAR(50) NOT NULL,
);

--INSERTAMOS VALORES--

INSERT INTO VENTA VALUES 
	(1, 6, '2023-01-06', 'VENDEDOR_PRO'),
	(3, 26, '2023-01-08', 'VENDEDOR_INICIAL'),
	(5, 16, '2023-01-08', 'VENDEDOR_PRO'),
	(14, 56, '2023-01-09', 'VENDEDOR_INTERMEDIO'),
	(7, 4, '2023-01-10', 'VENDEDOR_INICIAL'),
	(15, 116, '2023-01-11', 'VENDEDOR_PRO'),
	(4, 86, '2023-01-12', 'VENDEDOR_PRO'),
	(1, 26, '2023-01-13', 'VENDEDOR_INICIAL'),
	(23, 326, '2023-01-16', 'VENDEDOR_INTERMEDIO'),
	(20, 8, '2023-01-20', 'VENDEDOR_INICIAL'),
	(35, 416, '2023-01-22', 'VENDEDOR_PRO'),
	(23, 148, '2023-01-25', 'VENDEDOR_INTERMEDIO'),
	(45, 38, '2023-01-28', 'VENDEDOR_INICIAL');
GO

SELECT * FROM VENTA
GO

--EL VENDEDOR PRO PUEDE VISUALIZAR TODAS LAS VENTAS--
--EL VENDEDOR INTERMEDIO VE FILAS DONDE VENDEDOR SERA IGUAL A "VENDEDOR INTERMEDIO" O "VENDEDOR PRO" PERMITIENDO QUE SE CREEN OTROS USUARIOS CON LOW-RIGTHS EN EL FUTURO--
--EL VENDEDOR INICIAL SOLO VISUALIZA DONDE VENDEDOR SEA IGUAL A "VENDEDOR INICIAL"

CREATE FUNCTION dbo.administradoporusuario$predicadodeseguridad (@administradoporusuario AS sysname) 
RETURNS TABLE 
WITH SCHEMABINDING 
AS 
RETURN (SELECT 1 AS administradoporusuario$predicadodeseguridad 
           WHERE @administradoporusuario = USER_NAME() --(SI)administradoporusuario = NOMBRE DE USUARIO DE LA BASE DE DATOS 
               OR (USER_NAME() = 'VENDEDOR_INTERMEDIO' and @administradoporusuario <> 'VENDEDOR_PRO') --(SI) el usuario es VENDEDOR_INTERMEDIO Y VENDEDOR_PRO NO ADMINISTRA LA FILA--
               OR (USER_NAME() = 'VENDEDOR_PRO')); --(SI) SI EL USUARIO ES VENDEDOR_PRO PUEDE VER TODO
GO

--CREAMOS LA POLITICA DE SEGURIDAD--

CREATE SECURITY POLICY AdministradoPorUsuarioPolicy
ADD FILTER PREDICATE dbo.administradoporusuario$predicadodeseguridad(VENDEDOR) ON dbo.VENTA
GO

--ACTIVAMOS LA POLITICA DE SEGURIDAD--

ALTER SECURITY POLICY AdministradoPorUsuarioPolicy WITH (STATE = ON)

--IMPERSONAMOS CON LOS DISTINTOS USUARIOS--

GRANT SELECT ON VENTA TO VENDEDOR_INICIAL

EXECUTE AS USER='VENDEDOR_INICIAL'

SELECT * FROM VENTA
GO

REVERT

------------------------------------------
GRANT SELECT ON VENTA TO VENDEDOR_INTERMEDIO

EXECUTE AS USER='VENDEDOR_INTERMEDIO'

SELECT * FROM VENTA
GO

REVERT

------------------------------------------
GRANT SELECT ON VENTA TO VENDEDOR_PRO

EXECUTE AS USER='VENDEDOR_PRO'

SELECT * FROM VENTA
GO

REVERT

------------------------------------------









